include(InstallRequiredSystemLibraries)


set(CPACK_PACKAGE_VENDOR "Alvaro Denis Acosta Quesada")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Instalador de ${CMAKE_PROJECT_NAME} para el manejo bla bla")


#set(CPACK_GENERATOR "TGZ"), esto desabilita el .sh
set(CPACK_RESOURCE_FILE_WELCOME ${Project_DIRECTORY}/Readme/HACKING)
SET(CPACK_RESOURCE_FILE_LICENSE ${Project_DIRECTORY}/Readme/LICENSE.txt)
set(CPACK_RESOURCE_FILE_README  ${Project_DIRECTORY}/README.md)

# version for tarball name:
set(CPACK_PACKAGE_VERSION_MAJOR ${${CMAKE_PROJECT_NAME}_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${${CMAKE_PROJECT_NAME}_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${${CMAKE_PROJECT_NAME}_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})

set(CPACK_PACKAGING_INSTALL_PREFIX /tmp)
install(FILES ${CPACK_RESOURCE_FILE_LICENSE} DESTINATION share/doc/${CMAKE_PROJECT_NAME})
install(FILES ${CPACK_RESOURCE_FILE_README}  DESTINATION share/doc/${CMAKE_PROJECT_NAME})
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/Code/${CMAKE_PROJECT_NAME} DESTINATION /bin)



include(CPack)
